CREATE TABLE IF NOT EXISTS USERS(
   ID  SERIAL PRIMARY KEY,
   USERNAME           VARCHAR(256)      NOT NULL,
   PASSWORD       VARCHAR(512)       NOT NULL
);


INSERT INTO USERS (USERNAME, PASSWORD) VALUES  ('user1', 'user1');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES  ('user2', 'user1');